### ISSUE TITLE
promptBeta NLS formula

### ISSUE THREAD

**Issue by bbcho** [risktoollib/RTL#3]
you might get a better fit to the beta curve if you add a third degree of freedom using a constant bias. So the formula would be beta ~ x0*exp(x1*prompt)+x2

**Comment by risktoollib** [comment]
Nice to have new faces looking at it! Will add it to the dev list since the last time we fitted this was years ago. The main enhancement on this function I have in mind is to complement it with the forward looking betas using implied vols on the futs as well as implied correlations from Calendar Spread Options - at least for the front year.

**Comment by bbcho** [comment]
Also, you should exclude the first beta since it's always 1. If you include it, the model tries to fit a sharp discontinuity between the front month and second contract, impacting the fit for the entire model.

**Comment by risktoollib** [comment]
I removed the stats output for practical reasons. 
1) Futures contracts are discrete and practically fitting into a continuous function is of little practical use. The nature of markets dynamics makes them extremely sensitive to the time period chosen. In day to day trading (e.g. market making hedging a swap trade), the main value is knowing the approximate betas ranges for curve dynamics market risk management.    
2) In the event a used wanted to fit it, say for a project valuation simulation, it's best to extract the output = "data" and leave it to the user to do the modelling.
